### ISSUE TITLE
Authorization doesnt complete while using Homestead.

### ISSUE THREAD

**Issue by bad33ndj3** [JohnTheGr8/Wox.Plugin.Spotify#10]
### Issue Description

When confirming authorization for the wox.Spotify plugin my personal website project(Homestead) shows up on localhost:8000 so the authorization doesnt complete.

Which means I cant use this plugin and work at the same time.

I would love to know how I could fix this or if there are any plans on not using localhost:8000 for authorization.

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [X] Searching Spotify for albums, artists or songs
- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)

### Software Versions

Please fill in the following information:

- Spotify client version 1.0.77.338.g758ebd78
- Wox version 1.3.524

**Comment by Alexwijn** [comment]
Dit you try to change the default port of Homestead? https://laravel.com/docs/5.6/homestead#ports

**Comment by JohnTheGr8** [comment]
thanks @Alexwijn for providing @bad33ndj3 with a workaround. 

I switched the port to 8580 which should be in use less frequently than port 8000.
