### ISSUE TITLE
Always shows "No track playing"

### ISSUE THREAD

**Issue by mavanmanen** [JohnTheGr8/Wox.Plugin.Spotify#5]
Wox v1.3.183

Just added this plugin to my fresh install but it does not seem to be working, displays "No track playing" every time.

**Comment by JohnTheGr8** [comment]
Make sure the Spotify client is already running when you start Wox.
( I tried with the new release and it works as expected. )

Cheers

**Comment by mavanmanen** [comment]
I do start Spotify before Wox and it doesn't work fully still.
Searching is working, but playing songs or play/pause/next/mute are not at all.

I have Spotify v1.0.37.150.gad02a02e

**Comment by JohnTheGr8** [comment]
I published a new version, can you check and let me know if it works now?

**Comment by mavanmanen** [comment]
Replaced the plugin with the 2.0.0 version you have in here; still didn't work, no idea why.
Any information I could provide to you that would be useful?

**Comment by JohnTheGr8** [comment]
That's the old version, the new version was published on Wox's package manager.  I published it here on github as well, now. It's version 2.1.0.

Just uninstall the plugin with `wpm uninstall Wox.Spotify` and reinstall it.

Thank you

**Comment by mavanmanen** [comment]
Everything except skipping tracks is working right now.

**Comment by JohnTheGr8** [comment]
Okay, that's good. `Next` does occasionally glitch out for me as well, I'll have to look into it...

Thank you for reporting this issue and testing the fix.

Have a nice day!
