### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by jamy015** [JohnTheGr8/Wox.Plugin.Spotify#7]
### Issue Description

Hi, just installed the plugin but it doesn't do anything :( Even the local stuff like `sp pause` doesn't work.

### Functionality Affected

- [x] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [x] Searching Spotify for albums, artists or songs

### Software Versions

- Spotify client version (`Help > About Spotify`): 1.0.66.478.g1296534d
- Wox version (`Wox Settings > About`): 1.3.424

**Comment by GeorgeHahn** [comment]
Workaround: drop the latest release of [SpotifyAPI-NET](https://github.com/JohnnyCrazy/SpotifyAPI-NET) into the plugin's directory.

**Comment by JohnTheGr8** [comment]
thanks @GeorgeHahn 

I made a quick release to update to the latest release of SpotifyAPI-NET. Seems to work fine for me, let me know how it works for you...

Cheers

**Comment by GeorgeHahn** [comment]
Works for me, thanks!

**Comment by jamy015** [comment]
Works for me too 🎉
