### ISSUE TITLE
Spotify running but not detected

### ISSUE THREAD

**Issue by JonhyDread** [JohnTheGr8/Wox.Plugin.Spotify#8]
### Issue Description

Running 'sp play' (or any other command) makes wox display 'Spotify is not running' (while spotify is running)

### Functionality Affected

Controlling the local Spotify client (changing track, pausing, skipping, muting)
or, more specifically, detecting that Spotify is running

### Software Versions

- Spotify client version (`Help > About Spotify`): 1.0.75.483.g7ff4a0dc
- Wox version (`Wox Settings > About`): 1.3.524

Main problem is that I have a laptop running exactly the same versions of both programs (freshly installed on both), and it works there. I have tried reinstalling the wox spotify plugin, but still, it seems like it just doesnt detect spotify running there. Have restarted Wox, spotify and my computer as well.

**Comment by JonhyDread** [comment]
Just found out the reason:

![spotuf](https://user-images.githubusercontent.com/19312555/37425271-a7f1dbc8-27ba-11e8-9622-71b0547ba253.png)

'Allow Spotify to be opened from the web' has to be turned on in the settings. I had it enabled on my laptop and disabled on the desktop.
Please add that to your plugin description :)

**Comment by JohnTheGr8** [comment]
thank you for reporting (and finding the solution). 

I have updated the readme to include this notice.
